### ISSUE TITLE
connect pages to the navbar

### ISSUE THREAD

**Issue by hariomkushwaha** [dscabesit/playactivity#1]
connect the related pages to the navbar

**Comment by ACakshay** [comment]
I would like to work on it

**Comment by ManojAthreya** [comment]
I would like to work on this

**Comment by swas1820** [comment]
I would like to work on this. I have made a pull request kindly go through it.
Will be thankful.

**Comment by chandankumar1307** [comment]
I would like to work on this issue...Please assign me and it will be completed very soon.

**Comment by saiharsha-22** [comment]
@hariomkushwaha I have solved the issue you can merge into the repo #56

**Comment by ritinharizzieri** [comment]
I would like to work on it
