### ISSUE TITLE
add description on the pages

### ISSUE THREAD

**Issue by hariomkushwaha** [dscabesit/playactivity#10]
add description were its mention as add description

**Comment by igu** [comment]
assign to me, pls

**Comment by RAM-BHARATH** [comment]
Assign this to me.

**Comment by shivamguptaram** [comment]
please assign this issue to me

**Comment by Vansh1067** [comment]
I would like to do this please assign me

**Comment by ritinharizzieri** [comment]
I would like to work on this issue please

**Comment by hariomkushwaha** [comment]
it
