### ISSUE TITLE
add more items to the pages

### ISSUE THREAD

**Issue by hariomkushwaha** [dscabesit/playactivity#31]

**Comment by ashvinimore** [comment]
Hello Hari OM,
Can You assign me the task?
Thank You

**Comment by hariomkushwaha** [comment]
go for it

**Comment by deespider** [comment]
I will be giving pull requests after its done

**Comment by hariomkushwaha** [comment]
sure ! go for it

**Comment by preeti-1999** [comment]
I have added information to the pages and also fixed some links.Kindly review the changes and merge if helpful

**Comment by Yavush** [comment]
Hello I am new to Github, I tried adding a new search bar to the game page. I hope you like it :)
