### ISSUE TITLE
Bug: README needs more information and markdown formatting

### ISSUE THREAD

**Issue by kdipippo** [dscabesit/playactivity#37]
I'm not sure why the commit with new info was added as-is. The README can make use of markdown formatting in order to better render on GitHub. For more information: https://guides.github.com/features/mastering-markdown/

I also recommend instead of the copy-paste on how to contribute to this repo to link to the Hacktoberfest tutorial for contributing. If there are notes about contributing, I recommend that they're more about Code of Conduct, any information about the tech stack, etc. and not about how to use GIT (something project specific, if that makes sense).

Also, please add a section at the top of the README that explains what this project is. My proposed blurb would be: "A website to test out HTML and CSS formatting skills for Hacktoberfest."

**Comment by VARhimank** [comment]
Please assign me only then i can start working on this ! Thanks

**Comment by VARhimank** [comment]
I can do the formatting of readme to make it attractive <3

**Comment by hariomkushwaha** [comment]
@VARhimank go for it

**Comment by VARhimank** [comment]
> @VARhimank go for it

Can you please provide your social media contact if any and what things i should add ?

**Comment by VARhimank** [comment]
> @VARhimank go for it

PR sent please check and accept. Also can you add "hacktoberfest-accepted" label to it please ! :)
