### ISSUE TITLE
make a footer for home page

### ISSUE THREAD

**Issue by hariomkushwaha** [dscabesit/playactivity#5]

**Comment by ani-coder-hacker** [comment]
I'd like to work on designing a footer!

**Comment by Malvika18** [comment]
I would also like to work on this

**Comment by ani-coder-hacker** [comment]
Do I make a footer like that present on the other pages?

**Comment by Malvika18** [comment]
@hariomkushwaha hey i have made the pull request please check it.

**Comment by nipunwijetunge** [comment]
I'd like to work on this.

**Comment by ritinharizzieri** [comment]
I would like to work on this issue
