### ISSUE TITLE
fix the bug in home page

### ISSUE THREAD

**Issue by sachin-chauhan127** [dscabesit/playactivity#61]
bug in css sheet, there is a irregular arrangement of content which conflicting other component of the page

**Comment by sachin-chauhan127** [comment]
I would like to work on this issue

**Comment by caseymhunt** [comment]
I noticed while working this issue that you've included bootstrap but are not using it, electing instead to use your own column/grid system. I recommend either...
* removing the bootstrap dependency
* removing your custom columns and use bootstraps
* (recommended) look into a utility class system such as [Tailwind](https://tailwindcss.com/) which closely matches the kinds of techniques I see already in use in this project.
