### ISSUE TITLE
make the readme.md file

### ISSUE THREAD

**Issue by hariomkushwaha** [dscabesit/playactivity#8]

**Comment by rahmatullah5** [comment]
@hariomkushwaha I'd to work on this task, please invite my account to this repo as a contributor.
Thanks in advances

**Comment by madhhuurrii** [comment]
@hariomkushwaha I would like to contribute, please assign me if possible

**Comment by hariomkushwaha** [comment]
go ahead

**Comment by madhhuurrii** [comment]
@hariomkushwaha can u please assign me , ill submit my PR by tomorrow

**Comment by rahmatullah5** [comment]
@hariomkushwaha ya, could you invite us to the repo ?

**Comment by hariomkushwaha** [comment]
@rahmatullah5 Fork it and make a PR

**Comment by chandankumar1307** [comment]
I can make a very beautiful readme for you..please let me contribute

**Comment by hariomkushwaha** [comment]
@chandankumar1307 okay I assign you

**Comment by chandankumar1307** [comment]
Till when can I submit the readme?

**Comment by chandankumar1307** [comment]
I need to upload the Screen Shot of your website in the repository so that It can be used in the readme file. Please grant me access to the same.

**Comment by hariomkushwaha** [comment]
@chandankumar1307 yes you can

**Comment by chandankumar1307** [comment]
@hariomkushwaha 
I have updated the readme file and already given you a pr.
Please respond to it.
